// Labels use patient laterality; keys remain provider IDs, not anatomical sides.
const muscleLateralitySchema = 'bodyheatmap-1.0.0-patient-v1';
const regionLabels = <String, String>{
  "back-arm-left": "Bras · dos · droite du patient",
  "back-arm-right": "Bras · dos · gauche du patient",
  "back-butt-left": "Fesse · dos · droite du patient",
  "back-butt-right": "Fesse · dos · gauche du patient",
  "back-hand-left": "Main · dos · droite du patient",
  "back-hand-right": "Main · dos · gauche du patient",
  "back-head": "Tête · dos",
  "back-leg-left": "Membre inférieur · dos · droite du patient",
  "back-leg-right": "Membre inférieur · dos · gauche du patient",
  "back-mid-left": "Dos moyen / bas · dos · droite du patient",
  "back-mid-right": "Dos moyen / bas · dos · gauche du patient",
  "back-neck-left": "Cou · dos · droite du patient",
  "back-neck-right": "Cou · dos · gauche du patient",
  "back-shoulder-left": "Épaule · dos · droite du patient",
  "back-shoulder-right": "Épaule · dos · gauche du patient",
  "back-upper-left": "Haut du dos · dos · droite du patient",
  "back-upper-right": "Haut du dos · dos · gauche du patient",
  "front-abs": "Abdomen · face",
  "front-arm-left": "Bras · face · droite du patient",
  "front-arm-right": "Bras · face · gauche du patient",
  "front-chest-left": "Thorax · face · droite du patient",
  "front-chest-right": "Thorax · face · gauche du patient",
  "front-foot-left": "Pied · face · droite du patient",
  "front-foot-right": "Pied · face · gauche du patient",
  "front-head": "Tête · face",
  "front-hip-left": "Hanche · face · droite du patient",
  "front-hip-right": "Hanche · face · gauche du patient",
  "front-knee-left": "Genou · face · droite du patient",
  "front-knee-right": "Genou · face · gauche du patient",
  "front-leg-left": "Membre inférieur · face · droite du patient",
  "front-leg-right": "Membre inférieur · face · gauche du patient",
  "front-neck-left": "Cou · face · droite du patient",
  "front-neck-right": "Cou · face · gauche du patient",
  "front-palm-left": "Paume · face · droite du patient",
  "front-palm-right": "Paume · face · gauche du patient",
  "front-shoulder-left": "Épaule · face · droite du patient",
  "front-shoulder-right": "Épaule · face · gauche du patient",
};
